### ISSUE TITLE
Compilation error with ref type

### ISSUE THREAD

**Issue by Tormund** [status-im/nim-json-serialization#11]
```nim
import json_serialization

type
    DummyRef* = ref object of RootObj
        a: float
var dr = new(DummyRef)
dr.a = 100225.00
echo "resref:\n\t", dr.toJson 
```
nim-stew\stew\shims\macros.nim(43, 28) Error: index 2 not in 0 .. -1

**Comment by zah** [comment]
I've tried to investigate this and so far I'm hitting into insurmountable Nim issues in the behaviour of functions such as `getType` and `getImpl`. The issues seems to be affecting only types using the `ref object` short-cut. Everything is fine if you use the following approach instead:

```nim
import
  ../json_serialization

type
  DummyObj* = object of RootObj
    a: float

  DummyRef = ref DummyObj

var dr = new(DummyRef)
dr.a = 100225.00
echo "resref:\n\t", dr.toJson
```

**Comment by jangko** [comment]
nice, it works. I agree this is Nim compiler internal inconsistency.

**Comment by zah** [comment]
This should now work fine if you use Nim 1.2
