### ISSUE TITLE
Strange dependency tree

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-json-serialization#25]
I'm not sure why nim-json-serialization depends on BearSSL or Chronos, that seems very wrong.

![image](https://user-images.githubusercontent.com/22738317/103948153-9b92b180-5139-11eb-852f-aa25fca604eb.png)

**Comment by SolitudeSF** [comment]
faststreams has chronos integration

**Comment by mratsim** [comment]
I think faststreams is lower level than Chronos so:
- either we have optional dependencies in nimble and faststreams optionally depend on Chronos
- or chronos depends on faststreams, and the faststreams integration is built directly in Chronos. Which will be needed for async channels in any case https://github.com/status-im/nim-chronos/pull/45

**Comment by jangko** [comment]
fixed by status-im/nim-faststreams#38, closing
