### ISSUE TITLE
Error: undeclared identifier: 'findFieldIdx'

### ISSUE THREAD

**Issue by gogolxdong** [status-im/nim-json-serialization#51]
`/mnt/c/Users/low/.nimble/pkgs/json_serialization-0.1.0/json_serialization/reader.nim(638, 26) Error: undeclared identifier: 'findFieldIdx'
candidates (edit distance, scope distance); see '--spellSuggest':
 (5, 6): 'findFieldReader' [proc declared in /mnt/c/Users/low/.nimble/pkgs/serialization-0.1.0/serialization/object_serialization.nim(239, 6)]`

when building nimbus-eth1

**Comment by jangko** [comment]
nimbus-eth1 should be build using specific set of dependencies with specific commit hash. They can be found inside vendor folder of nimbus-eth1. And then dependencies paths should be generated using makefile.
OP question seems using nimble which is downloading incompatible sets of dependencies(incompatible commit hash).
Closing as this is not nim-json-serialization problem.
